language: node_js
node_js:
- v10
- node
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
script:
  - npm test -- -i --coverage
env:
  global:
  - CXX=g++-4.8
  - MASTER_KEY=masterKey
  - JWT_SECRET=jwtSecret
  - DB_UNAME=admin
  - DB_PASS=password
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: HCmstcDxi6mnsKNBYfdClhvGZ4TFVmRLWvaIxrV5xNg6JArUmzl+VfzxpA86PDMCMQrxjJI67yWkE7lTqIKVKtz+GQlnwrloLMYGDlWdX9v1KPkoeraj+hTsQqPmzXc4dGPrCgBsVCXjJac1Kj3KjZFxDF2yx/pficOzpbAGhOhPEEkhIAuz4jduJmWJ1okgldKXro861OxsYfoylZWNUfV6hSlw2m3uplJDKZaLGvEH/5XhGYAA/FJ/KstURiDDaHt8XBSqKSoVgrHUxtz05VO+/WX2l6LWVjHS/UusXKCLG40mZxIgOz6KrjFF/tIcnlimqwfw1J8SJ/Lo8Z1u1sOtFp23XGD8fp05f11b+R7aWBlb9C2MDOh+qRMkS9a2LpQajKbTUK07sLGMT/RD5jbU823wKFhJy86tq6DIicQNC5rBh0HbBwfHi2Nj9ioL8trnXSRe7gQyDR2MDbVi5Iyo/cLRGf891CR6Q5xUfqMsy5XMib327IDt098/Ua04vhquQQ1ZPO9ZRZIpbyOOk7eepAZg/nONXWCRb68khLIc0kRFvqPmI9IE94CdNAFXEJfTg7lzxafrtMVk4xH8YonUMZBhyrIA4aXmC2d5hMLNcs0alUi+ewGMZvQkVWXFwNRy5pmVBd1zWYSyGJI7QXdkxcYjKn0ZpI7lyqQD+S4=
