language: node_js
node_js:
- v10
- v8.16
- node
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
script:
  - npm test -- -i --coverage
env:
  global:
  - CXX=g++-4.8
  - MASTER_KEY=masterKey
  - JWT_SECRET=jwtSecret
  - DB_UNAME=admin
  - DB_PASS=password
branches:
  only:
  - master
