version: 2.0 
jobs:
  build:
    docker: 
      - image: circleci/node:10.16.2
    steps: 
      - checkout
      - run:
          name: env file
          command: 'cp .env.example .env'
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: 
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-deps
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: 
          name: test
          command: npm test

